### ISSUE TITLE
Adding a parameter will cause a warning

### ISSUE THREAD

**Issue by execonic** [nerun/dokuwiki-plugin-templater#9]
#### Version
`Release 0.8.2 of 2023-12-07`

#### Issue
The **_templater_**  works fine when there is only section name. But when I add the parameter `title` to the **_templater_**, I get the following warning.
 `There's no such section "tpl" in the page [Sidebar Template]` 

<img src=https://github.com/nerun/dokuwiki-plugin-templater/assets/27429124/ef04a844-2a9a-47d4-bdcc-cc142b81550e width=400px />

**Comment by nerun** [comment]
Bug confirmed, thank you.

**Comment by nerun** [comment]
FIxed in 0.8.4 commit bb587b91163668dc377c6de792bbc66e48016e86, but `#ifemp` was removed, it's broken, don't understand why. It worked some days ago.
